IL 298 add product rating
Sunagatov/Iced-Latte pull request #246
Opened 2024-02-17 07:36 UTC by M437A

2024-02-17 14:52 UTC, annstriganova requested changes
Reviewed

2024-02-17 14:52 UTC, annstriganova commented on pom.xml
> +                                <apiPackage>${openapi-package}.order.api</apiPackage>
Copy-paste typo: replace `order.api` with `rating.api` 👍

2024-02-17 14:52 UTC, annstriganova commented on src/main/java/com/zufar/icedlatte/review/endpoint/RatingEndpoint.java
> +    public static final String RATING_URL = "/api/v1/rating/product";
I'd consider using `/api/v1/products/rating` and `/api/v1/products/review`, what do you think?

2024-02-17 14:52 UTC, annstriganova commented on src/main/java/com/zufar/icedlatte/review/endpoint/RatingEndpoint.java
> +public class RatingEndpoint {
You might have forgotten `implements` + `overrides`

2024-02-17 15:02 UTC, annstriganova commented on src/main/java/com/zufar/icedlatte/review/endpoint/RatingEndpoint.java
> +public class RatingEndpoint {
Nevermind, you fixed that in the second PR.

2024-02-18 15:35 UTC, Sunagatov reviewed
Reviewed

2024-02-18 15:35 UTC, Sunagatov commented on pom.xml
> +                            <inputSpec>${project.basedir}/src/main/resources/api-specs/rating-openapi.yaml</inputSpec>
```
product-rating-openapi.yaml
```
instead of
```
rating-openapi.yaml
```
please

2024-02-18 15:35 UTC, Sunagatov commented on src/main/java/com/zufar/icedlatte/review/endpoint/RatingEndpoint.java
> +    public static final String RATING_URL = "/api/v1/rating/product";
Please, make it like this:
```
HTTP POST api/v1/products/{productId}/rating
```

2024-02-18 15:35 UTC, Sunagatov commented on src/main/java/com/zufar/icedlatte/review/endpoint/RatingEndpoint.java
> +    public ResponseEntity<RatingDto> addNewMarkToProduct(@RequestBody final AddNewMarkToProductRequest rating) {
```ratingRequest``` instead of ```rating```

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/api-specs/rating-openapi.yaml
> +  /api/v1/products/rating:
Please, make it like this:
```
HTTP POST api/v1/products/{productId}/rating
```

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/api-specs/rating-openapi.yaml
> +        productId:
remove from requestBody

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/api-specs/rating-openapi.yaml
> +        userId:
remove userId

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/db/changelog/version-1.0/changelog-master-version-1.0.yaml
> +      file: db/changelog/version-1.0/15.02.2024.part1.create-rating-table.sql
product-create-rating-table.sql

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/api-specs/rating-openapi.yaml
> +    RatingDto:
ProductRatingDto

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/api-specs/rating-openapi.yaml
> +    AddNewMarkToProductRequest:
ProductRatingRequest

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/api-specs/rating-openapi.yaml
> +        mark:
rating

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/api-specs/rating-openapi.yaml
> +                value: {"productId": "a1b2c3d4", "mark": 5}
remove productId

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/api-specs/rating-openapi.yaml
> +      summary: "Add mark to product"
"Add rating to product"

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/api-specs/rating-openapi.yaml
> +        - "Rating"
ProductRating

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/api-specs/rating-openapi.yaml
> +        description: "Payload containing the product ID and mark."
rating instead of mark

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/api-specs/rating-openapi.yaml
> +      operationId: "addNewMarkToProduct"
addNewProductRating

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/api-specs/rating-openapi.yaml
> +                summary: "Add Mark"
rating instead mark

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/api-specs/rating-openapi.yaml
> +                value: {"productId": "a1b2c3d4", "mark": 5}
rating instead mark

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/db/changelog/version-1.0/15.02.2024.part1.create-rating-table.sql
> +    CONSTRAINT fk_product_rting
fk_product_rating

2024-02-18 15:35 UTC, Sunagatov commented on src/main/resources/db/changelog/version-1.0/15.02.2024.part1.create-rating-table.sql
> +    mark        INT  NOT NULL CHECK (mark > 0 AND mark < 6),
rating

2024-02-18 15:36 UTC, Sunagatov reviewed
reviewed

2024-02-18 15:36 UTC, Sunagatov commented on src/main/java/com/zufar/icedlatte/common/exception/handler/GlobalExceptionHandler.java
> +    public ApiErrorResponse handlePSQLException(final PSQLException exception) {
remove this handler

2024-02-25 11:40 UTC, annstriganova commented on src/main/java/com/zufar/icedlatte/review/endpoint/RatingEndpoint.java
> +    public static final String RATING_URL = "/api/v1/rating/product";
Zufar insists on `api/v1/products/{productId}/rating` https://github.com/Sunagatov/Iced-Latte/pull/246#discussion_r1493787143

2024-03-04 23:27 UTC, annstriganova requested changes
Reviewed

2024-03-04 23:27 UTC, annstriganova commented on pom.xml
> +                    <!-- Generate from Product productRating OpenAPI Spec -->
`Generate from Product productRating` -> `Generate from Product Rating`

2024-03-04 23:27 UTC, annstriganova commented on pom.xml
> +                        <id>generate-from-product-productRating-openapi-spec</id>
`productRating` -> `rating`

2024-03-04 23:27 UTC, annstriganova commented on pom.xml
> +                                <apiPackage>${openapi-package}.product.productRating.api</apiPackage>
`productRating` -> `rating`

2024-03-04 23:27 UTC, annstriganova commented on src/main/java/com/zufar/icedlatte/security/configuration/SpringSecurityConfiguration.java
> +                                .requestMatchers(SecurityConstants.RATING_URL).authenticated()
`GET` should be available for any user, consider using `.requestMatchers(HttpMethod.GET, SecurityConstants.RATING_URL)`

2024-03-04 23:27 UTC, annstriganova commented on src/main/java/com/zufar/icedlatte/security/jwt/JwtAuthenticationFilter.java
> +                        SecurityConstants.REVIEWS_URL, SecurityConstants.RATING_URL)
`GET` should be available for any user

2024-03-10 14:59 UTC, closed without merging